Promotions
SkyCryptWebsite/SkyCrypt pull request #1232
Opened 2022-03-18 21:07 UTC by metalcupcake5

- adds google form to the promotions
- allows "weighting" promotions to display some more than others
  - could probably be improved

2022-03-20 13:45 UTC, dukio commented
About the randomWeighted function did you write or find it?

I was looking at https://dev.to/trekhleb/weighted-random-algorithm-in-javascript-1pdc and their implementation is slightly different... if you found it I'm just wondering if it's accurate (the fact that it's not using `const` where it should be or returning from the last `for` instead of breaking out of it is kinda worring me)

2022-03-20 17:18 UTC, metalcupcake5 commented
> did you write or find it

i found it, i do agree it could use some changing though

2022-03-20 22:14 UTC, dukio requested changes

2022-03-20 22:14 UTC, dukio commented on src/lib.js
> +      item.extra.dye = item.tag.ExtraAttributes.dye_item;
Ehm... wrong base branch?

2022-03-20 22:14 UTC, dukio commented
> > did you write or find it
> 
> i found it, i do agree it could use some changing though. did some testing and it seems mostly accurate, i'll change a few things tho

👍

2022-03-21 15:45 UTC, metalcupcake5 commented on src/lib.js
> +      item.extra.dye = item.tag.ExtraAttributes.dye_item;
yikes mb

2022-03-21 16:06 UTC, dukio approved these changes

2022-03-21 16:13 UTC, merged