Fix JS failing when player hasn't done catacombs
SkyCryptWebsite/SkyCrypt pull request #1345
Opened 2022-04-30 15:13 UTC by Korase

2022-05-01 10:25 UTC, dukio approved these changes
looks good to me

But do you have a link to a profile where this failed? 🤔 
I tested with https://sky.shiiyu.moe/stats/DynamicEx/Lemon#Dungeons (a player who never played dungeons) and the JS is not failing 😕

2022-05-01 10:34 UTC, dukio requested changes
Actually hold on... maybe we should just check if the `calculated.dungeons.catacombs.level` exists, otherwise skip the block

Yeah I think that's cleaner... so just wrap everything in

```js
if (calculated.dungeons?.catacombs?.level) {
 // ...
}
```

2022-05-01 10:46 UTC, dukio commented
I went ahead and proposed a fix with Korase#1

2022-05-01 20:59 UTC, dukio approved these changes

2022-05-02 15:10 UTC, MartinNemi03 approved these changes

2022-05-02 15:16 UTC, merged