Change to github credits
SkyCryptWebsite/SkyCrypt pull request #148
Opened 2020-11-19 22:01 UTC by Pottedplant530

Gg i did a code

2020-11-20 01:57 UTC, nstringham commented
This should probably also be updated
![Screenshot_20201119-205557~2](https://user-images.githubusercontent.com/44071655/99748073-cc475a80-2aa9-11eb-8a86-1ba02b470146.jpg)

2020-11-20 18:14 UTC, boblovespi requested changes

2020-11-20 18:14 UTC, boblovespi commented on README.md
>  - **Player Heads**: <a href="https://hypixel.net/forums/skyblock.157/">SkyBlock</a> by Hypixel.
```suggestion
- **Player Heads**: <a href="https://hypixel.net/forums/skyblock.157/">SkyBlock</a> by Hypixel
```

2020-11-20 18:48 UTC, Pottedplant530 commented
alright @boblovespi I made the change, can you approve this

2021-01-02 19:22 UTC, Pottedplant530 commented
@boblovespi :|

2021-01-05 06:14 UTC, metalcupcake5 approved these changes

2021-03-09 20:28 UTC, vyketype requested changes
You put "Defualt Pack" in line 40. It should be "Default Pack".

2021-07-03 12:53 UTC, nstringham requested changes
Conflicts

2021-08-03 21:13 UTC, closed without merging