feat: (Piscary VI enchantment)
SkyCryptWebsite/SkyCrypt pull request #1644
Opened 2022-09-07 13:18 UTC by DuckySoLucky

2022-09-07 16:05 UTC, metalcupcake5 approved these changes
didnt test

2022-09-07 16:06 UTC, metalcupcake5 requested changes

2022-09-07 16:06 UTC, metalcupcake5 commented on common/constants/enchantments.js
> +  "Piscary VI",
move it up one to make it alphabetical

2022-09-07 16:45 UTC, metalcupcake5 approved these changes
lgtm didnt test

2022-09-07 20:48 UTC, dukio approved these changes
lgtm didn't test

2022-09-09 16:08 UTC, MartinNemi03 approved these changes
lgtm, didn't test

2022-09-09 16:09 UTC, merged