feat: proper recomb accessory count
SkyCryptWebsite/SkyCrypt pull request #1650
Opened 2022-09-11 06:39 UTC by metalcupcake5

closes #1637 
![image](https://user-images.githubusercontent.com/43897385/189515551-658d24b2-009b-44f3-b340-5dffc5d6e6cf.png)
on indigo_polecat/Pineapple

2022-09-12 18:38 UTC, dukio requested changes
Only a small thing then it's good to go for me (didn't test)

2022-09-12 18:38 UTC, dukio commented on src/constants/accessories.js
> +  if (ACCESSORIES[accessory]?.allowRecomb == false) {
I would make this a `===`

2022-09-12 18:39 UTC, metalcupcake5 commented
![image](https://user-images.githubusercontent.com/43897385/189730838-8bd4fe1f-b4c1-491e-813f-f619c74dfc93.png)
dont merge until i do this

2022-09-12 18:48 UTC, dukio commented
Also would it be more grammatically correct to use "allowsRecomb" (with s?)

2022-10-10 19:50 UTC, dukio approved these changes
I'll approve this, but the accessories stats need to be revisited in the future...

![image](https://user-images.githubusercontent.com/2744227/194941710-7872c28b-6110-429d-8c03-19071dfe554f.png)

Unique accessories is the number of unique accessories owned out of all the accessories that exist, correct.

Completion should be equivalent to "this person has this progress towards having every accessory upgraded to the max (recomb, enrichment, other stuff like max gemstones on artifact of power or pandora box challenges)"

Recombobulated should be, as it was before, "this person has recombobulated X accessories out of his total accessories owned that can be recombobulated", this PR changes this to "this person has X recombobulated accessoires out of all the accessories in existance that can be recombobulated" (so not just the owned ones)

2022-10-17 16:01 UTC, MartinNemi03 approved these changes
lgtm, didn't test

2022-10-20 10:29 UTC, merged