refactor: count Carpentry skill towards Skill Average
SkyCryptWebsite/SkyCrypt pull request #1655
Opened 2022-09-12 10:13 UTC by DuckySoLucky

## Description 

Closes #1602 

## Example
![image](https://user-images.githubusercontent.com/75372052/189629176-f326e23d-415a-47f7-a0e2-080ef4ea1d61.png)

2022-09-12 10:15 UTC, DuckySoLucky commented
Oops, branch was merged with #1654 ;-;
Doesn't really matter but still :/

2022-09-12 10:19 UTC, DuckySoLucky commented
Updated Description
![image](https://user-images.githubusercontent.com/75372052/189630332-2bff0e67-f028-4f44-bf46-278aee2175ec.png)

2022-09-12 18:25 UTC, dukio commented
![image](https://user-images.githubusercontent.com/2744227/189728488-d80bd669-d151-4eb6-9d4e-c55e8ffbce8b.png)
This gives NaN on senither skill on a profile with API off: http://localhost:32464/stats/dukioooo/Lemon

My solution would be to just hide weight if API is off, carpentry is a skill now so it must count towards weight... and without that the weight values are just wrong imo

2022-09-12 18:27 UTC, dukio requested changes
![image](https://user-images.githubusercontent.com/2744227/189728488-d80bd669-d151-4eb6-9d4e-c55e8ffbce8b.png)
This gives NaN on senither skill on a profile with API off: http://localhost:32464/stats/dukioooo/Lemon

My solution would be to just hide weight if API is off, carpentry is a skill now so it must count towards weight... and without that the weight values are just wrong imo

2022-09-12 18:27 UTC, DuckySoLucky commented
Sure, I guess 🤷‍♂️

2022-09-12 20:56 UTC, metalcupcake5 approved these changes
didnt test

2022-09-30 08:31 UTC, DuckySoLucky commented
@dukio Why waiting label?

2022-09-30 08:32 UTC, dukio commented
> @dukio Why waiting label? 

https://github.com/SkyCryptWebsite/SkyCrypt/pull/1655#discussion_r968825549

2022-09-30 11:47 UTC, dukio approved these changes
lgtm tested

2022-09-30 11:47 UTC, dukio commented on views/stats.ejs
>  ];
@DuckySoLucky I think you accidentally merged some changes from the sea creatures PR here

2022-09-30 11:47 UTC, dukio commented on views/stats.ejs
>  ];
@DuckySoLucky if you can just revert the changes to this array then this PR can go live 🙏

2022-09-30 11:47 UTC, dukio commented
@SkyCryptWebsite/developers 2 approvals 😄

2022-09-30 11:50 UTC, DuckySoLucky commented on views/stats.ejs
>  ];
> @DuckySoLucky if you can just revert the changes to this array then this PR can go live 🙏

Oops I thought I reverted that as well I guess not. Will update in like 5 hours when I get home

2022-09-30 17:18 UTC, DuckySoLucky commented on views/stats.ejs
>  ];
> @DuckySoLucky I think you accidentally merged some changes from the sea creatures PR here

Just checked file, I have actually fixed it. You were checking outdated file, it says on top as well

2022-10-01 13:32 UTC, MartinNemi03 requested changes
About weight systems, they don't seem to be working on any profiles.

2022-10-01 13:52 UTC, DuckySoLucky commented
> About weight systems, they don't seem to be working on any profiles.

Solved, accidentally reverted that as well ;-;

2022-10-01 22:05 UTC, MartinNemi03 approved these changes
lgtm, tested

2022-10-01 22:05 UTC, merged