Updated stats
SkyCryptWebsite/SkyCrypt pull request #1696
Opened 2022-10-01 12:59 UTC by DuckySoLucky

## Description

Uses base core from #1639 
Adds new stats
Shows more accurate stats (Tested on 2 profiles, accuracy is like 90-95%, mostly because of cookie and missing stuff in the API)

Closes #1393 

# Examples
![image](https://user-images.githubusercontent.com/75372052/193410309-d6689b60-2296-43ef-a867-e0d34030624b.png)
![image](https://user-images.githubusercontent.com/75372052/193410314-7a0a55c7-a9d5-46a9-9d18-3183f9b580eb.png)

2022-10-01 13:18 UTC, DuckySoLucky commented
Should not be merged before #1648 and #1651

2022-10-09 14:14 UTC, dukio requested changes
Didn't read through everything right now but I saw a couple things (see comments below).

Also this will need to get an upstream once bestiary PR gets merged, cuz right now it has bestiary things too

2022-10-09 14:14 UTC, dukio commented on public/resources/ts/calculate-player-stats.ts
> +import { REFORGES } from "../../../src/constants/reforges.js";
instead of importing everything it would be better to then just use `import * as CONTANTS from "../../../common/constants.js"`

2022-10-09 14:14 UTC, dukio commented on common/constants/bonuses.js
> +    25: { health: 0, farming_fortune: 0 },
![image](https://user-images.githubusercontent.com/2744227/194761308-c46d7cb9-5f78-40cb-b4fb-26ec3a142d5e.png)

?

2023-01-16 19:39 UTC, MartinNemi03 requested changes
tested on 56 profiles and found the following:
- stats don't load on: `Ephemera`, `Refraction`, `Technoblade`
- `selected_power` breaks `jjww2`'s profile

2023-01-16 20:29 UTC, DuckySoLucky commented
> tested on 56 profiles and found the following:
> 
> * stats don't load on: `Ephemera`, `Refraction`, `Technoblade`
> * `selected_power` breaks `jjww2`'s profile

Fixed

2023-08-08 13:29 UTC, closed without merging