feat: add Accessories bag data and axes to farming tools
SkyCryptWebsite/SkyCrypt pull request #1699
Opened 2022-10-03 12:33 UTC by DuckySoLucky

## Description

Closes #657 
Closes #1381 

## Examples
![image](https://user-images.githubusercontent.com/75372052/193577075-44c27230-4d5e-45d4-bb24-0fe7c42a1603.png)
![image](https://user-images.githubusercontent.com/75372052/193577092-3557ff06-dd55-4f31-b546-39688b63de11.png)
![image](https://user-images.githubusercontent.com/75372052/193577140-0d4173e5-3194-4d1b-982a-dd6ec27b9876.png)

2022-10-03 22:01 UTC, dukio reviewed
Couple things to review. In the future (or if you have time/will now) would be nice to also include the missing reforges (if they are not too many, maybe as a normal text list (`foo, bar and muu`)) + a count "unlocked 10 / 99"

2022-10-03 22:01 UTC, dukio commented on src/lib.js
> +      a.categories?.includes("farming_tool") ||
my initial idea when doing the categories was to find a place in lib.js where we could add a bunch of IFs like
`if item.id === "MELON_DICER", item.categories.push("farming_tool")`
so that if we need to print farming tools in different placed we dont have to rememeber all the exceptions.

would you mind looking for a solution like this instead? could be useful in the future for other things too (not just farming tools maybe, but other categories too)

2022-10-03 22:01 UTC, dukio commented on views/stats.ejs
> +            <% max = calculated.accessory_bag_storage.bag_upgrades_purchased >= 99 ? 'golden-text' : '' %>
the 99 I would make it a CONSTANT, better to not hardcode values outside constants folder

2022-10-05 10:40 UTC, DuckySoLucky commented on src/lib.js
> +      a.categories?.includes("farming_tool") ||
Updated in latest commit

2022-10-05 10:40 UTC, DuckySoLucky commented on views/stats.ejs
> +            <% max = calculated.accessory_bag_storage.bag_upgrades_purchased >= 99 ? 'golden-text' : '' %>
Done in latest commit

2022-10-06 22:35 UTC, dukio requested changes
Does this still includes treecaps for you too?

2022-10-06 22:36 UTC, dukio commented
![image](https://user-images.githubusercontent.com/2744227/194430946-900f022d-6112-4a4b-89f3-12153e25bc5e.png)
http://localhost:32464/stats/Refraction/Apple#Skills

For some weird reason it also puts treecapitators in... it does it with any of these conditions `itemId === "MELON_DICER" || itemId === "PUMPKIN_DICER" || itemId === "COCOA_CHOPPER"` but not if you do like `itemId === "xxx"` which is even weirder... 

There must be something that I'm missing o-ò

2022-10-23 11:55 UTC, DuckySoLucky commented
> Does this still includes treecaps for you too?

Fixed, still not sure what's the cause :/

2023-02-24 12:37 UTC, DuckySoLucky commented
There's new PR for accessories

2023-02-24 12:37 UTC, closed without merging