fix: Pet Score MF Symbol
SkyCryptWebsite/SkyCrypt pull request #1756
Opened 2022-11-03 15:42 UTC by DuckySoLucky

## Description

Fixes https://canary.discord.com/channels/738971489411399761/738990246825427084/1036219139108380752
> TL;DR Calculation would put pointing arrow to closest value even without meeting requirements

Example: https://sky.shiiyu.moe/stats/dukioooo/Raspberry#Pets

## Example
> Before

![image](https://user-images.githubusercontent.com/75372052/199767060-9eac3d9b-efa9-4fe4-8264-fbf2cc5b4455.png)

> After

![image](https://user-images.githubusercontent.com/75372052/199767012-115ef9cf-b997-47c5-afa4-a93166f71d16.png)

2022-11-06 09:53 UTC, MartinNemi03 approved these changes
lgtm, didn't test

2022-11-08 09:10 UTC, Shiiyu requested changes
Instead of such a crude workaround, I'd suggest it to be changed to findLast() instead, as discussed earlier, requesting changes here so it isn't accidentally merged from Martin's approval.

2022-12-02 16:07 UTC, DuckySoLucky commented
> Instead of such a crude workaround, I'd suggest it to be changed to findLast() instead, as discussed earlier, requesting changes here so it isn't accidentally merged from Martin's approval.

Done but different way, `.findLast()` doesn't seem to work. Check discord for more information

2022-12-02 19:05 UTC, Shiiyu approved these changes
LGTM

2022-12-02 19:06 UTC, merged