fix: Farming Level capped at 50 if skills API off
SkyCryptWebsite/SkyCrypt pull request #1838
Opened 2023-01-27 19:48 UTC by DuckySoLucky

## Description

Fixes https://canary.discord.com/channels/738971489411399761/748625263893545042/1066876666619646064
> `Math.max()` can be used safely here since hypixel returns true level from achievements

## Example
> Before

![image](https://user-images.githubusercontent.com/75372052/215183420-82afda2b-1a2f-4100-b51b-51ae89aadd82.png)
> After

![image](https://user-images.githubusercontent.com/75372052/215183302-7807e3ec-eb39-469a-a305-99d6d078aa4f.png)

2023-01-29 01:57 UTC, WarpWing requested changes
Could we use OR statements here instead? Not to sound pedantic but instead, you could use || instead of ??. So it would look like

```js
const levelCap = extra.cap ||  (uncappedLevel > (extra.skill in constants.DEFAULT_SKILL_CAPS ? constants.DEFAULT_SKILL_CAPS[extra.skill] : uncappedLevel)) || Math.max(...Object.keys(xpTable));
```

2023-02-05 13:39 UTC, MartinNemi03 commented
> 

Not really sure what would the benefit be there, maybe once it would be prettified it would be better, but from this it doesn't look any better, at least only from the looks of it.

2023-02-05 13:53 UTC, DuckySoLucky commented
> > Could we use OR statements here instead? Not to sound pedantic but instead, you could use || instead of ??. So it would look like
> > ```js
> > const levelCap = extra.cap ||  (uncappedLevel > (extra.skill in constants.DEFAULT_SKILL_CAPS ? constants.DEFAULT_SKILL_CAPS[extra.skill] : uncappedLevel)) || Math.max(...Object.keys(xpTable));
> > ```
> 
> Not really sure what would the benefit be there, maybe once it would be prettified it would be better, but from this it doesn't look any better, at least only from the looks of it.

https://canary.discord.com/channels/738971489411399761/820755886262976553/1069171051268952166
We talked about it, `??` would be better in this case

2023-02-05 14:47 UTC, MartinNemi03 approved these changes
lgtm, didn't test

2023-02-05 14:49 UTC, merged