feat: add bank cooldown amount
SkyCryptWebsite/SkyCrypt pull request #1927
Opened 2023-04-10 00:20 UTC by Zickles

feat: add bank cooldown amount

## Example

![image](https://user-images.githubusercontent.com/76439587/230791578-a5563c67-c7da-4813-a7f0-994a95cd2e2e.png)

2023-04-10 08:51 UTC, DuckySoLucky approved these changes
~~lgtm, small suggestion: add `maxed` value, that's gonna make value gold if it's maxed (needs to get implemented in stats.ejs)~~
Added

2023-04-10 12:36 UTC, DuckySoLucky commented
![image](https://user-images.githubusercontent.com/75372052/230902571-868efd19-e08e-4f95-aec5-d508f55250f7.png)

2023-04-26 16:11 UTC, metalcupcake5 approved these changes

2023-04-26 16:15 UTC, metalcupcake5 requested changes
i lied run prettier 👍

2023-04-27 21:48 UTC, metalcupcake5 approved these changes

2023-04-27 21:48 UTC, merged