Replace current system with cookies
SkyCryptWebsite/SkyCrypt pull request #41
Opened 2020-09-05 21:50 UTC by metalcupcake5

2020-09-06 04:01 UTC, boblovespi requested changes
Cookies do not persist on browser close/reopen

2020-09-07 18:47 UTC, boblovespi requested changes
Please make it show the currently selected pack

2020-09-07 20:42 UTC, boblovespi approved these changes

2020-09-07 21:03 UTC, WarpWing commented
Since Bob has approved these changes, I'm going to merge. YEEET

2020-09-07 21:03 UTC, merged