Add first version of Themes
SkyCryptWebsite/SkyCrypt pull request #54
Opened 2020-09-12 19:05 UTC by MartinNemi03

So it works like this: 
- Themes are stored in src/constants/themes.js
- When a site is requested, it loads in with extra
- Default theme is "default", automatically selected, when "currentTheme" isn't stored in LocalStorage

Please review and give feedback.
Let's hope this doesn't break.

2020-09-12 20:01 UTC, boblovespi requested changes
themes and packs can be open at the same time

2020-09-12 20:20 UTC, MartinNemi03 commented
> 
> 
> themes and packs can be open at the same time

i forgot that. ok, gimme a moment.

2020-09-12 21:45 UTC, metalcupcake5 requested changes
Looks good

2020-09-12 21:45 UTC, metalcupcake5 commented on src/constants/themes.js
> +            name: "sky.lea.moe's Theme",
```suggestion
            name: "sky.lea.moe",
```
imo "sky.lea.moe" sounds better than "sky.lea.moe's theme"

2020-09-12 21:59 UTC, metalcupcake5 approved these changes
Looks good

2020-09-12 22:02 UTC, boblovespi requested changes
![image](https://user-images.githubusercontent.com/22250834/93005748-d9275b00-f508-11ea-9038-38645685f863.png)
you can't select certain packs on mobile

2020-09-13 00:21 UTC, boblovespi approved these changes

2020-09-13 00:22 UTC, merged