Added the megalodon pet
SkyCryptWebsite/SkyCrypt pull request #67
Opened 2020-09-17 14:30 UTC by felix642

Added the pet description to the website. It's only missing a texture.

2020-09-17 14:31 UTC, felix642 commented
![image](https://user-images.githubusercontent.com/60141446/93485274-e78ec180-f8d0-11ea-874e-cc1b9ec1b17b.png)

2020-09-17 16:14 UTC, metalcupcake5 requested changes
Also please move the multiplier above the return statement to keep with the other pet stat classes.
For example, turn this
```
get first() {
    return {
        name: "§6Blood Scent",
        desc: [`§7Deal up to §c+${round(0.25*this.level,1)}% ${symbols.strength} §7Damage based on the enemy's missing health`]
    };
}
```
into this
```
get first() {
    let mult = 0.25;
    return {
        name: "§6Blood Scent",
        desc: [`§7Deal up to §c+${round(this.level * mult,1)}% ${symbols.strength} §7Damage based on the enemy's missing health`]
    };
}
```

2020-09-17 16:14 UTC, metalcupcake5 commented on src/constants/petStats.js
> +			desc: [`On kill gain §c${0.5 * this.level}${symbols.strength} Damage §7and §f${symbols.speed} speed for 5 seconds`]
```suggestion
			desc: [`§7On kill gain §c${0.5 * this.level}${symbols.strength} Damage §7and §f${symbols.speed} Speed §7for 5 seconds`]
```

2020-09-17 16:19 UTC, metalcupcake5 commented
Also you can get the head from the NBT, should be pretty easy.

2020-09-17 16:24 UTC, felix642 commented
How am I suppose to get the NBT ?

2020-09-18 00:15 UTC, metalcupcake5 commented
Using sba you can copy item NBT

2020-09-18 01:02 UTC, felix642 commented
![image](https://user-images.githubusercontent.com/60141446/93543253-1a64a400-f929-11ea-9ea1-c0c660c6ec44.png)

2020-09-18 12:41 UTC, boblovespi requested changes

2020-09-18 12:41 UTC, boblovespi commented on src/constants/petStats.js
> +			desc: [`§7On kill gain §c${mult * this.level}${symbols.strength} Damage §7and §f${symbols.speed} speed §7for 5 seconds`]
Speed should be capitalized, no?

2020-09-18 12:41 UTC, boblovespi commented on src/constants/petStats.js
> +		let mult = 0.25
missing a semicolon
```suggestion
		let mult = 0.25;
```

2020-09-20 18:18 UTC, metalcupcake5 approved these changes

2020-09-24 17:37 UTC, boblovespi approved these changes

2020-09-24 17:39 UTC, merged