Thread and Database Abstraction and Optimisation
SkyCryptWebsite/SkyCrypt pull request #755
Opened 2021-08-23 03:09 UTC by nstringham

Changes:
- only run app.js on non-master threads
- only run scripts on master thread
- only make one MongoDB instance per thread
- only make one Redis instance per thread
- allow redis URL to be configured and update Docs

close #722 
close #723

2021-08-23 03:11 UTC, nstringham commented
@Flou21 can you make sure this works with your Redis setup

2021-08-23 07:31 UTC, dukio requested changes

2021-08-23 07:31 UTC, dukio commented on CONTRIBUTING.md
> +6. (optional) If you are not using the default Redis port or you are using Redis remotely, you can configure the Redis URL with the `redisUrl` felid in `credentials.json`
Typo, "felid" instead of field

2021-08-23 17:09 UTC, nstringham commented on CONTRIBUTING.md
> +6. (optional) If you are not using the default Redis port or you are using Redis remotely, you can configure the Redis URL with the `redisUrl` felid in `credentials.json`
Thanks

2021-08-23 17:23 UTC, MartinNemi03 approved these changes
Good job with this @nstringham.
LGTM, didn't test!

2021-08-23 19:01 UTC, Flou21 commented
> @Flou21 can you make sure this works with your Redis setup

yes it does solve my problem as well, thanks

2021-08-30 16:49 UTC, metalcupcake5 approved these changes

2021-08-30 16:49 UTC, metalcupcake5 commented on src/app.js
> +// this file never run on the master thread
```suggestion
// this file never runs on the master thread
```
slight grammar adjustment :)

2021-08-31 21:13 UTC, merged