Lit: skill-component
SkyCryptWebsite/SkyCrypt pull request #938
Opened 2021-11-05 18:28 UTC by dukio

Merge #936 before this, there will be conflicts after the merge so tag me and I'll fix them

---

Converts `skill_component()` to Lit `skill-component`

Stuff changed:
- tippy will no longer be displayed if `data-tippy-content=""` (empty string), before it would still show the `*` and the tooltip but with Lit components it's much easier to handle it this way so that you can do `condition ? html'<span>tooltip</span>' : ""` without having to worry about an empty tooltip appearing
- copied `formatNumber()` from helper.js to `stats-defer.ts` (used in `skill-component.ts`)

First time using Lit so... let me know if I did anything wrong or if anything can be improved 😄

2021-11-05 19:53 UTC, nstringham commented
> with Lit components it's much easier to handle it this way so that you can do `condition ? html'<span>tooltip</span>' : ""` without having to worry about an empty tooltip appearing

You should do undefined instead of empty string

2021-11-06 12:15 UTC, dukio commented
> > with Lit components it's much easier to handle it this way so that you can do `condition ? html'<span>tooltip</span>' : ""` without having to worry about an empty tooltip appearing
> 
> You should do undefined instead of empty string

Changed in 922359dbdb0fc8be8fd4ba97010eb7b4b5d8dedb, thanks

Had to use `ifDefined()` (otherwise there was a ts error) so now the check if `data-tippy-content` is empty is no longer required, should I revert that change or can it be useful in the future?

2021-11-07 16:33 UTC, nstringham commented
> Had to use `ifDefined()`

yep that's the recommended method for optional properties


> now the check if `data-tippy-content` is empty is no longer required, should I revert that change or can it be useful in the future?

I would probably revert it. it will be easy to add it back in if we need that in the future.

2021-11-07 17:54 UTC, nstringham requested changes
I left comments on a number of issues

some of them are fixed by https://github.com/dukio/SkyCrypt/pull/90 others still need to be fixed

2021-11-07 17:54 UTC, nstringham commented on public/resources/ts/stats-defer.ts
> +import("./elements/skill-component");
this element is above the fold so it should not be lazily loaded

2021-11-10 22:38 UTC, dukio commented
> > Had to use `ifDefined()`
> 
> yep that's the recommended method for optional properties
> 
> > now the check if `data-tippy-content` is empty is no longer required, should I revert that change or can it be useful in the future?
> 
> I would probably revert it. it will be easy to add it back in if we need that in the future.

reverted in ef249fc59cde084296f964355c4bbae1c57e6eb9

2021-11-10 22:38 UTC, dukio commented on public/resources/ts/elements/skill-component.ts
> +  skill: string | undefined = undefined;
ty!

2021-11-10 22:43 UTC, dukio commented on public/resources/ts/elements/skill-component.ts
> +  if (!("runecrafting" in calculated.levels)) {
Progression can only be calculated if user has skills API enabled, we can check if he user has the API enabled by checking if we have runecrafting data, which is not present in the achievements (the place where we get the skills if skills API is disabled).

2021-11-10 23:05 UTC, dukio commented on public/resources/ts/elements/skill-component.ts
> +    @mouseover="${(e: MouseEvent) => {
Nope... but I see now... tomorrow I'll try to figure out how to do this

2021-11-15 12:44 UTC, dukio commented on public/resources/ts/elements/skill-component.ts
> +    @mouseover="${(e: MouseEvent) => {
Refactored in 1b80434

2021-12-30 21:24 UTC, dukio commented
👋 ?

2021-12-30 21:32 UTC, dukio commented
Converting to draft until I can resolve the conflicts (vscode detects 10.000+ changes and it's basically stuck trying to process what's going on 🙄 )

2021-12-30 21:46 UTC, dukio commented
Resolved conflicts.

@nstringham fyi `interfact Level` was missing the property `rank: number;` ... idk if it was left out on purpose?

2022-01-03 03:31 UTC, nstringham commented on public/resources/ts/globals.d.ts
> +  rank: number;
should be `rank?: number;`

2022-01-03 13:58 UTC, dukio commented on public/resources/ts/globals.d.ts
> +  rank: number;
fixed, thanks ce5089d

2022-01-03 19:24 UTC, nstringham commented on public/resources/ts/globals.d.ts
> +  rank: number;
Np

2022-01-08 12:11 UTC, dukio commented
Resolved conflict

2022-01-17 03:38 UTC, nstringham requested changes
Overall looks pretty good.

I have created https://github.com/dukio/SkyCrypt/pull/106 which resolves CSS merge conflicts and changes how the hover state works to something that seems more readable and performant to me

I still don't like how it takes like half a second for the skill bars to load in after everything else above the fold is loaded but that should get better as we move more of the page to client side rendering.

2022-01-17 03:38 UTC, nstringham commented on public/resources/ts/elements/skill-component.ts
> +              ${this.progressText === "Loading..." ? this.getProgressTexts()[0] : this.progressText}
If the loading text is never displayed then there is no point in putting it there in the first place

2022-01-28 23:09 UTC, dukio commented
Merged Nate's dukio#106 which fixes a lot of things I had no clue how to fix... (thanks)

ready for review now, tested in local and works fine on multiple profiles I checked

2022-01-31 16:08 UTC, MartinNemi03 approved these changes

2022-01-31 23:45 UTC, nstringham commented on public/resources/ts/elements/skill-component.ts
> +    return [mainText, hoverText];
fixed in https://github.com/SkyCryptWebsite/SkyCrypt/commit/0adf990b68fe86a526c500b8ab9f4348bb25f3b5

2022-01-31 23:47 UTC, nstringham commented on public/resources/ts/elements/skill-component.ts
> +    this.progressText = string;
fixed in https://github.com/SkyCryptWebsite/SkyCrypt/commit/13176fc1c312f3e0a8583798e9a9f5042e3d8a1a

2022-01-31 23:47 UTC, nstringham commented on public/resources/ts/elements/skill-component.ts
> +  private _updateProgressText(string: string) {
fixed in https://github.com/SkyCryptWebsite/SkyCrypt/commit/13176fc1c312f3e0a8583798e9a9f5042e3d8a1a

2022-01-31 23:49 UTC, nstringham commented on public/resources/ts/elements/skill-component.ts
> +              ${this.progressText === "Loading..." ? this.getProgressTexts()[0] : this.progressText}
fixed in https://github.com/SkyCryptWebsite/SkyCrypt/commit/13176fc1c312f3e0a8583798e9a9f5042e3d8a1a

2022-02-01 00:01 UTC, nstringham approved these changes
Everything looks good (except for performance as previously discussed)

2022-02-01 07:27 UTC, merged