Updated Dungeons section (Boss Collections)
SkyCryptWebsite/SkyCrypt pull request #96
Opened 2020-10-06 21:21 UTC by MartinNemi03

- Changed constants for boss collections
- Updated boss collections to count tier completions
- Added option to max a boss collection

2020-10-06 21:24 UTC, metalcupcake5 approved these changes
~~martin stop spamming me kthx bai~~
Looks good

2020-10-06 22:02 UTC, boblovespi requested changes
![image](https://user-images.githubusercontent.com/22250834/95264820-df95b380-07e4-11eb-8059-381ea977048c.png)
you need commas when number of kills > 1000

2020-10-06 22:02 UTC, boblovespi commented on src/lib.js
> +            console.log(collections[floor_id]);
please remove

2020-10-06 22:22 UTC, MartinNemi03 commented on src/lib.js
> +            console.log(collections[floor_id]);
cough, cough.. you've seen nothing

2020-10-07 19:01 UTC, boblovespi approved these changes

2020-10-07 19:49 UTC, merged

2020-10-07 19:49 UTC, metalcupcake5 commented
Martin you can delete the branch if you want